### ISSUE TITLE
Since, until and limit are not lists when subscribing with filter

### ISSUE THREAD

**Issue by dsbaars** [riccardobl/nostrduino#1]
Hi, great work on this library already! 

When creating a filter with since, until and limit I get an error from relay when subscribing because those values aren't list (unlike kinds and authors, which are).

**Comment by riccardobl** [comment]
Thank you. 
Fixed  in version 1.2.7 .
You don't need to change anything in your filter definition, the subscribeMany handles the conversion internally.
